### ISSUE TITLE
The import 'werkzeug.cached_property' is deprecated

### ISSUE THREAD

**Issue by LaundroMat** [pytest-dev/pytest-flask#106]
I ran into this issue using Werkzeug 1.0.0RC1 with pytest-flask:

`ImportError: cannot import name 'cached_property' from 'werkzeug' (c:\***\.virtualenvs\***-ceh2yp3w\lib\site-packages\werkzeug\__init__.py)` 

The current version of Werkzeug (0.16.1) gives a deprecation warning for this import:

    >>> from werkzeug import cached_property
    __main__:1: DeprecationWarning: The import 'werkzeug.cached_property' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.utils import cached_property' instead.

I'm unable to do a PR now, but I thought I'd log the issue here already.

**Comment by nicoddemus** [comment]
Thanks @LaundroMat!

We already have https://github.com/pytest-dev/pytest-flask/pull/105 in place, it should be merged soon. 👍

**Comment by LaundroMat** [comment]
Duh, I never checked the PR's 🙄 I'll close this :)

**Comment by nicoddemus** [comment]
No worries, it would close this automatically once the PR gets merged. 👍

**Comment by nicoddemus** [comment]
0.15.1 has been released to PyPI. 👍

**Comment by retr0h** [comment]
I'm still seeing the same problem with pytest-flask.

```
[jodewey:~/git/meta-release] update-model(+1/-0) ± pip freeze | grep pytest-flask
pytest-flask==0.15.1
```
