### ISSUE TITLE
Live Server with Session Scope

### ISSUE THREAD

**Issue by TWood67** [pytest-dev/pytest-flask#112]
Creating a live server is expensive, especially when its done for every function. Is it possible to have different options when it comes to scope? I'd like to create a live server that lasts for the entire session. I'd be more than happy to contribute and add this functionality.

**Comment by nicoddemus** [comment]
Hi @TWood67,

Thanks for the offer!

Yes I think this would be a nice functionality to add, we might even consider using [dynamic scopes](https://docs.pytest.org/en/latest/fixture.html#dynamic-scope) for that.

**Comment by yujinyuz** [comment]
There was a previous attempt to make the `live_server` to use the `session` scope here: https://github.com/pytest-dev/pytest-flask/pull/63

But it's been 2 years since he made the PR.

I'm hoping for this feature to be implemented soon

**Comment by TWood67** [comment]
Thanks for the help! I'll check out #63 and see where I can go from there

**Comment by nicoddemus** [comment]
I suggest to take a different approach than #63 though: you the example of dynamic scopes I posted earlier so that you can control the scope of the live-server fixture from the command-line/ini option (I would go with the latter).
