### ISSUE TITLE
Package documentation outdated

### ISSUE THREAD

**Issue by hynek** [pytest-dev/pytest-flask#118]
Your documentation at https://pytest-flask.readthedocs.io/en/latest/ hasn't [built in over two years](https://readthedocs.org/projects/pytest-flask/builds/) and the changelog ends with 0.10.  

I'm surprised I'm the only one noticing (or I'm bad at using the search function) – is there some other documentation somewhere else?  This is the once linked from the README.

**Comment by nicoddemus** [comment]
Thanks @hynek!

Unfortunately I don't have access to the readthedocs project, but I have contacted the maintainer (@vitalk) to give me access. 👍

**Comment by northernSage** [comment]
@nicoddemus any news on this?

**Comment by nicoddemus** [comment]
No, radio silence unfortunately.

I contacted readthedocs, hopefully they will solve that for us.

**Comment by nicoddemus** [comment]
The readthedocs support replied today already (awesome support): they will follow their [policy for abandoned project](https://docs.readthedocs.io/en/stable/abandoned-projects.htm) asking to add me as maintainer, and if they don't reply in 6 weeks they will give me permission.

Thanks again for the ping!

**Comment by northernSage** [comment]
That was fast, nice support indeed. If there's anything else I can do to help just let me know 👍🏻

**Comment by nicoddemus** [comment]
Good news, the readthedocs support has granted me access to the project. I've already built a new version and re-synchronized the webhook. 👍 

@northernSage what's your username on readthedocs?

**Comment by northernSage** [comment]
That's great! 

My RTD username is **northernSage**

**Comment by nicoddemus** [comment]
Cool, done!
