### ISSUE TITLE
cannot import name 'cached_property' from 'werkzeug' 

### ISSUE THREAD

**Issue by bbbart** [pytest-dev/pytest-flask#119]
Hi,

After updating to werkzeug==1.0.0 and pytest-flask==1.0.0 my tests stopped working with an `ImportError: cannot import name 'cached_property' from 'werkzeug'`.

Replacing `from werkzeug import cached_property` with `from werkzeug.utils import cached_property` in `pytest_flask/plugin.py` fixes this.

**Comment by OrkoHunter** [comment]
Looks like `pytest_flask/plugin.py` has been updated with the fix 
https://github.com/pytest-dev/pytest-flask/blob/ba8b83f7ce91678704708fdd399264dc57c672ee/pytest_flask/plugin.py#L12

However, a release might be required?

As of now, it is broken. :( [My CI build](https://travis-ci.org/github/OrkoHunter/pep8speaks/builds/670887717?utm_source=github_status).

**Comment by OrkoHunter** [comment]
This issue has been fixed in the pytest-flask version `>=0.15.1`. 🎉

**Comment by bbbart** [comment]
thanks a lot!
