### ISSUE TITLE
Wrong color formatting output.

### ISSUE THREAD

**Issue by SebFernandez** [pytest-dev/pytest-flask#134]
**Context**
I'm using Pytest to test a Flask webapp, when I execute my tests there is one of them that FAILS at the middel of the sequence, so the format of the following text will be red instead of green when they PASS.

**Steps to reproduce**: 
1. Create a set of tests.
2. Place one test that will **fail** in order to be executed at the middle of the test execution.

**Expected behavior**
Wheter the test fails the color will be red and if it's a pass, the color will be green.

**Screenshots**
[Here's a screenshot of the issue](https://imgur.com/oqGbbme.png)
[VS Code detailed information](https://imgur.com/FKBo6Yl.png)

**Environment:**
 - OS: Xubuntu 20.10
 - Python Version 3.8.6
 - Pytest version 6.2.2
 - Flask version 1.1.2

**Additional context**
I'm using a Terminal hosted by VS Code (v1.53.2)

**Comment by northernSage** [comment]
Hey @SebFernandez , thanks for taking the time to open the issue. Pytest-flask is not responsible for console output (and its colour schema). It provides a layer between Flask and Pytest, it's a set of tools for testing Flask applications and related extensions. This issue probably belongs to [pytest](https://github.com/pytest-dev/pytest) itself

I will be closing this for now, thanks for your contribution!

**Comment by SebFernandez** [comment]
I see... my bad. Thanks for the response!
