### ISSUE TITLE
Comply with PEP 517

### ISSUE THREAD

**Issue by HLFH** [pytest-dev/pytest-flask#159]
**Is your feature request related to a problem? Please describe.**
Setup.py and setup.cfg are obsolete.

**Describe the solution you'd like**
[Comply with PEP 517](https://peps.python.org/pep-0517/) and add `pyproject.toml`.

**Describe alternatives you've considered**
None

**Additional context**
```
**/usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
**
```

**Comment by vitalk** [comment]
Hello @HLFH 

The latest released version (1.3.0) is PEP 517 compatible and contains `pyproject.toml`. Kudos to @nicoddemus
