### ISSUE TITLE
Consider moving to pytest-dev?

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-flask#41]
Hi @vitalk,

Just noticed your plugin, what do you think about moving it under the [pytest-dev](https://github.com/pytest-dev) organization? The idea is to provide more visibility and avoid plugins to become abandoned (which is obviously not the case with `pytest-flask`). You keep sole admin permissions over the repository, releases, etc etc... the only thing that changes in practice is that now it lives under the `pytest-dev` namespace.

**Comment by vitalk** [comment]
@nicoddemus looks good for me. Can you provide a more detailed description about how the moving occurs?

**Comment by nicoddemus** [comment]
Sure! :smile: 

1. Send a pytest-dev@python.org requesting the transfer... we had decided that at least two core maintainers should give :+1: based if the plugin meets the [pre-requisites](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst#id8), which you do already except by having a `tox` file.

2. We create a `pytest-flask-admins` with administrative privileges and invite you to it. 

3. You can transfer the repository under your control at pytest-dev and add other contributors as you see fit.

Sorry, just now I noticed you lack a `tox.ini` file... would you consider add one? We think it is important as it gives contributors a straightforward way to run the tests and is compatible with the [plugincompat](plugincompat.herokuapp.com) service.

**Comment by vitalk** [comment]
Well, I'll include a `tox.ini` in a few days and then submit a request.

**Comment by nicoddemus** [comment]
Great!

**Comment by steenzout** [comment]
@nicoddemus @vitalk #48 will close this.

**Comment by steenzout** [comment]
tox added.

**Comment by RonnyPfannschmidt** [comment]
oh, had i been aware of that one earlier i wouldnt have asked the question on the ml

**Comment by nicoddemus** [comment]
:+1:
