### ISSUE TITLE
Testing errors when streaming

### ISSUE THREAD

**Issue by cknv** [pytest-dev/pytest-flask#42]
I currently have a problem with errors when I try to test a streaming endpoint, namely when I use the `stream_with_context` flask function/decorator to keep the context around, as I am streaming from a database which client is on `current_app`.

Essentially, the test passes, but then pytest-flask errors with a message about it having popped the wrong request context:
`AssertionError: Popped wrong request context.  (<RequestContext 'http://localhost/stream' [GET] of app> instead of <RequestContext 'http://localhost/' [GET] of app>)`

Or at least I think it's pytest-flask.

I have a small gist that demonstrates the issue: https://gist.github.com/cknv/152d81ffcc4a74be491d, though it might be a little on the primitive side, but for me it does demonstrate the error. If you need some more information, I would of course be more than happy to provide it :)

For completeness sake, I am running python 3.5.

**Comment by vitalk** [comment]
Thank you for detailed description. I never used `stream_with_context` before and a some time required to dig into your issue.

**Comment by cknv** [comment]
I hadn't either until recently :) So I understand if you might need to learn a little more about some internals.

I am not sure if it's possible, but I would be ok with having a decorator to tell pytest-flask that this is a streaming endpoint, although that might not be so very clean.

**Comment by vitalk** [comment]
As workaround I suggest you to replace `yield_fixture` to `fixture` for `client` definition:

```python
@pytest.fixture
def client(app):
    return app.test_client()
```

But you are unable to access request context (`request`/`session`/etc) in your suite as mentioned in [documentation](http://pytest-flask.readthedocs.org/en/latest/features.html#request-ctx-request-context) and should push context explicitly when request context is required: 

```python
def test_request_ctx(client):
    with client:
        res = client.get(url_for('index'), headers=[('X-Something', '42')])
        assert request.headers['X-Something'] == '42'
```

**Comment by cknv** [comment]
Aha, yes that works. I generally don't often need the request context around in the test, so I can live with that.

I must admit that I copied that fixture from another flask app without thinking too much about it. Which was probably also copied from somewhere else, etc, etc.

Would it be fitting still to make pytest-flask better able to handle streaming, or would it be good enough to just document the dos and don'ts of testing streaming?

**Comment by vitalk** [comment]
Maybe I'll remove a `yield_fixture` (and related request context) at all in the next release for the sake of streaming support.

**Comment by dusktreader** [comment]
@vitalk I just ran into the same issue. Creating a fixture in my conftest file for client as you suggested seemed to fix things:
```
   @pytest.fixture
   def client(app):
       return app.test_client()
```

**Comment by pbabbicola** [comment]
Is this "fix" still working? I am running into the same problem here and creating a fixture and explicitly pushing the context is not working for me.

**Comment by fantix** [comment]
This is actually a bug in `flask.testing.FlaskClient` - entering a client preserves all context from being poped, but exiting only poped one preserved context:

https://github.com/pallets/flask/blob/c5c8bbc7f699de6b81ebd9893dc0a2289ae688dc/flask/testing.py#L203-L217

If there're multiple preserved contexts, an outer pop would fail:

```python
import flask

app = flask.Flask(__name__)


@app.route("/hello")
def hello():
    with flask._request_ctx_stack.top:
        return flask.Response("hello")


with app.test_request_context():
    with app.test_client() as client:
        resp = client.get("/hello")
        print(resp.data)
```

```
hello
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    print(resp.data)
  File "site-packages/flask/ctx.py", line 399, in __exit__
    self.auto_pop(exc_value)
  File "site-packages/flask/ctx.py", line 387, in auto_pop
    self.pop(exc)
  File "site-packages/flask/ctx.py", line 379, in pop
    '(%r instead of %r)' % (rv, self)
AssertionError: Popped wrong request context.  (<RequestContext 'http://localhost/hello' [GET] of t4> instead of <RequestContext 'http://localhost/' [GET] of t4>)
```

### Temporary Solution

Above example is the same underlying code when `pytest_flask` is used together with `stream_with_context`. A simple fix would be to override the `client` fixture, and clean up all preserved context:

```python
@pytest.yield_fixture
def client(app):
    """
    Overriding the `client` fixture from pytest_flask to fix this bug:
    https://github.com/pytest-dev/pytest-flask/issues/42
    """
    with app.test_client() as client:
        yield client

    while True:
        top = flask._request_ctx_stack.top
        if top is not None and top.preserved:
            top.pop()
        else:
            break
```

**Comment by davidism** [comment]
A fix was previously merged in to Flask, but I'm now reverting that. The behavior described here is correct. The context for `stream_with_context` is preserved separately from `with client`, and should remain as long as the generator is still running. Your test either needs to read `response.data`, or call `response.close()`. Either of those will close the generator and release the context.
