### ISSUE TITLE
HTTP request using 'live_server'

### ISSUE THREAD

**Issue by jeff1evesque** [pytest-dev/pytest-flask#45]
I took a `live_server` [example](https://pytest-flask.readthedocs.io/en/latest/features.html#live-server-application-live-server), and placed it on the root of [my project](https://github.com/jeff1evesque/machine-learning) (not committed), as `manager.py`:

``` python
# @manager.py

import urllib2
from flask import Flask, url_for
import pytest

def test_add_endpoint_to_live_server(live_server):
    @live_server.app.route('/load-data/')
    def test_endpoint():
        return 'got it', 200

    live_server.start()

    res = urllib2.urlopen(url_for('test_endpoint', _external=True))
    assert res.code == 200
```

Then, defined a very simple `conftest.py`, also on the root of  [my project](https://github.com/jeff1evesque/machine-learning) (not committed):

``` python
#confteset.py

from factory import create_app

@pytest.fixture
def app():
    app = create_app()
    return app
```

My `pytest.ini`, is pretty simple as well, and again on the root of  [my project](https://github.com/jeff1evesque/machine-learning) (not committed):

``` ini
[pytest]
python_files=manager.py
python_classes=Test
python_functions=test
```

I've attempted to implement `py.test` several different ways in terminal (vagrant vm):

``` bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ cd /vagrant
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ py.test
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 320, in
_importconftest
    mod = conftestpath.pyimport()
  File "/usr/local/lib/python2.7/dist-packages/py/_path/local.py", line 650, in
pyimport
    __import__(modname)
  File "/vagrant/conftest.py", line 17, in <module>
    from factory import create_app
  File "/vagrant/factory.py", line 20, in <module>
    from interface.views import blueprint
  File "/vagrant/interface/views.py", line 10, in <module>
    from brain.load_data import Load_Data
ImportError: No module named brain.load_data
ERROR: could not load /vagrant/conftest.py

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python -m pytest manager.py
============================= test session starts ==============================

platform linux2 -- Python 2.7.6, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /vagrant, inifile: pytest.ini
plugins: flask-0.10.0
collected 1 items

manager.py F

=================================== FAILURES ===================================

_______________________ test_add_endpoint_to_live_server _______________________


live_server = <LiveServer listening at http://localhost:51685>

    def test_add_endpoint_to_live_server(live_server):
        @live_server.app.route('/load-data/')
        def test_endpoint():
            return 'got it', 200

        live_server.start()

>       res = urllib2.urlopen(url_for('test_endpoint', _external=True))

manager.py:30:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

/usr/lib/python2.7/urllib2.py:127: in urlopen
    return _opener.open(url, data, timeout)
/usr/lib/python2.7/urllib2.py:410: in open
    response = meth(req, response)
/usr/lib/python2.7/urllib2.py:523: in http_response
    'http', request, response, code, msg, hdrs)
/usr/lib/python2.7/urllib2.py:448: in error
    return self._call_chain(*args)
/usr/lib/python2.7/urllib2.py:382: in _call_chain
    result = func(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _


self = <urllib2.HTTPDefaultErrorHandler instance at 0x7f4e9eb567e8>
req = <urllib2.Request instance at 0x7f4e9eb6d290>
fp = <addinfourl at 139975646958944 whose fp = <socket._fileobject object at 0x7
f4e9eb92dd0>>
code = 405, msg = 'METHOD NOT ALLOWED'
hdrs = <httplib.HTTPMessage instance at 0x7f4e9eb6d518>

    def http_error_default(self, req, fp, code, msg, hdrs):
>       raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
E       HTTPError: HTTP Error 405: METHOD NOT ALLOWED

/usr/lib/python2.7/urllib2.py:531: HTTPError
----------------------------- Captured stderr call -----------------------------

Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pytest_flask/fixtures.py", line 5
9, in <lambda>
    worker = lambda app, port: app.run(port=port, use_reloader=False)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 694, i
n run_simple
    inner()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 656, i
n inner
    fd=fd)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 550, i
n make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 464, i
n __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
=========================== 1 failed in 2.27 seconds ===========================
```

I spent this past weekend, and a few days last week after work, trying to understand `pytest`.  I noticed pytest-flask, and really like the rst files being generated to the [documentation](https://pytest-flask.readthedocs.io/en/latest/features.html).  But, I haven't been successful implementing the above example taken straight out from the [`live_server`](https://pytest-flask.readthedocs.io/en/latest/features.html#live-server-application-live-server) documentation.  My overall goal, is to have pytest-flask start a flask instance (app context?).  This flask instance (i.e. `http://localhost:xxxx`), would exist for the duration, or scope of the unit testing.  Specifically, I need the flask instance to be running, and I want to run some of my general [programmatic_interface](https://github.com/jeff1evesque/machine-learning/tree/master/test/programmatic_interface) tests.  Later, I will drill down, and have more specific unit tests.

I've been going back and forth, trying to implement `live_server`, and `client.post()`.  However, the documentation very lightly discusses about `client.get()`, and never mentions the existence of `client.post()`.  I was hoping if I used `live_server`, I would have a flask instance (i.e. `http://localhost:xxxx`), which would exist for the duration of the implemented unit tests.  But, I wasn't sure if I need to cleverly integrate `client.post()` within the `live_test` implementation.

**Comment by vitalk** [comment]
Hi @jeff1evesque!

> error: [Errno 98] Address already in use

The error occurs because your trying to launch the server which already has been started:

```python
 live_server.start()
```

If you want to prevent starting server automatically use `--no-start-live-server` option when running `pytest` (e.g. via cli or `pytest.ini` as [mentioned in documentation](https://pytest-flask.readthedocs.io/en/latest/features.html#no-start-live-server-dont-start-live-server-automatically)).

> However, the documentation very lightly discusses about client.get(), and never mentions the existence of client.post

`pytest-flask` itself [relies on the internal Flask API](https://pytest-flask.readthedocs.io/en/latest/features.html#client-application-test-client) and creates the default [Flask.test_client] (http://flask.pocoo.org/docs/0.11/api/#flask.Flask.test_client) client instance which works like a regular [Werkzeug test client](http://werkzeug.pocoo.org/docs/0.11/test/#werkzeug.test.Client) and has all methods it provides (`open`, `get`, `post`, etc). Documentation don‘t describe this methods because this is part of the flask/werkzeug documentation, but I agreed that for developers who don‘t know flask testing internals this is not obvious and better include some note about them.

**Comment by jeff1evesque** [comment]
I tried one of your suggestions:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ py.test --no-start-live-server
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 320, in
_importconftest
    mod = conftestpath.pyimport()
  File "/usr/local/lib/python2.7/dist-packages/py/_path/local.py", line 650, in
pyimport
    __import__(modname)
  File "/vagrant/conftest.py", line 17, in <module>
    from factory import create_app
  File "/vagrant/factory.py", line 20, in <module>
    from interface.views import blueprint
  File "/vagrant/interface/views.py", line 10, in <module>
    from brain.load_data import Load_Data
ImportError: No module named brain.load_data
ERROR: could not load /vagrant/conftest.py

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python -m pytest --no-start-live-ser
ver manager.py
============================= test session starts ==============================

platform linux2 -- Python 2.7.6, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /vagrant, inifile: pytest.ini
plugins: flask-0.10.0
collected 1 items

manager.py .

=========================== 1 passed in 1.10 seconds ===========================
```

But, only the second attempt work, and I'm not sure it even ran the test.  Why did the first attempt not work?  Additionally, I decided to adjust the `pytest.ini`:

```ini
[pytest]
python_files=manager.py
python_classes=Test
python_functions=test
addopts = --no-start-live-server
```

Is `addopts` supposed to be `adopts`.  The following are the two attempts with the above adjustment, which produced similar results:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ py.test
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 320, in
_importconftest
    mod = conftestpath.pyimport()
  File "/usr/local/lib/python2.7/dist-packages/py/_path/local.py", line 650, in
pyimport
    __import__(modname)
  File "/vagrant/conftest.py", line 17, in <module>
    from factory import create_app
  File "/vagrant/factory.py", line 20, in <module>
    from interface.views import blueprint
  File "/vagrant/interface/views.py", line 10, in <module>
    from brain.load_data import Load_Data
ImportError: No module named brain.load_data
ERROR: could not load /vagrant/conftest.py

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python -m pytest manager.py
============================= test session starts ==============================

platform linux2 -- Python 2.7.6, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /vagrant, inifile: pytest.ini
plugins: flask-0.10.0
collected 1 items

manager.py .

=========================== 1 passed in 1.10 seconds ===========================
```

Do you have any suggestions regarding my above comment:

>I spent this past weekend, and a few days last week after work, trying to understand `pytest`.  I noticed pytest-flask, and really like the rst files being generated to the [documentation](https://pytest-flask.readthedocs.io/en/latest/features.html).  But, I haven't been successful implementing the above example taken straight out from the [`live_server`](https://pytest-flask.readthedocs.io/en/latest/features.html#live-server-application-live-server) documentation.  My overall goal, is to have pytest-flask start a flask instance (app context?).  This flask instance (i.e. `http://localhost:xxxx`), would exist for the duration, or scope of the unit testing.  Specifically, I need the flask instance to be running, and I want to run some of my general [programmatic_interface](https://github.com/jeff1evesque/machine-learning/tree/master/test/programmatic_interface) tests.  Later, I will drill down, and have more specific unit tests.

>I've been going back and forth, trying to implement `live_server`, and `client.post()`.  However, the documentation very lightly discusses about `client.get()`, and never mentions the existence of `client.post()`.  I was hoping if I used `live_server`, I would have a flask instance (i.e. `http://localhost:xxxx`), which would exist for the duration of the implemented unit tests.  But, I wasn't sure if I need to cleverly integrate `client.post()` within the `live_test` implementation.

**Comment by jeff1evesque** [comment]
I tried the following `manager.py`:

```python
# @manager.py

import urllib2
from flask import Flask, url_for
import pytest
import json
import os.path

def test_add_endpoint_to_live_server(accept_json, client, live_server):
    @live_server.app.route('/load-data/')
    def get_endpoint():
        return url_for('name.load_data', _external=True)

    live_server.start()

    res = client.post(
        get_endpoint(),
        headers={'Content-Type': 'application/json'},
        data=get_sample_json('svm-data-new.json', 'svm')
    )

    print res
    assert res.code == 200

def get_sample_json(jsonfile, model_type):
    '''@get_sample_json

    Get a sample json dataset.

    '''

    json_dataset = None
    with open(
        '/vagrant/' + os.path.join(
            'interface',
            'static',
            'data',
            'json',
            'programmatic_interface',
            model_type,
            jsonfile
        ),
        'r'
    ) as json_file:
        json_dataset = json.load(json_file)
    return json.dumps(json_dataset)
```

Which generated the following traceback:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python -m pytest -s
============================= test session starts ==============================

platform linux2 -- Python 2.7.6, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /vagrant, inifile: pytest.ini
plugins: flask-0.10.0
collected 1 items

manager.py <<class 'pytest_flask.plugin.JSONResponse'> streamed [200 OK]>
F

=================================== FAILURES ===================================

_______________________ test_add_endpoint_to_live_server _______________________


accept_json = [('Accept', 'application/json')]
client = <FlaskClient <Flask 'vagrant.factory'>>
live_server = <LiveServer listening at http://localhost:45776>

    def test_add_endpoint_to_live_server(accept_json, client, live_server):
        @live_server.app.route('/load-data/')
        def get_endpoint():
            return url_for('name.load_data', _external=True)

        live_server.start()

        res = client.post(
            get_endpoint(),
            headers={'Content-Type': 'application/json'},
            data=get_sample_json('svm-data-new.json', 'svm')
        )

        print res
>       assert res.code == 200
E       AttributeError: '<class 'pytest_flask.plugin.JSONResponse'>' object has
no attribute 'code'

manager.py:37: AttributeError
========================== 1 failed in 22.73 seconds ===========================
```

**Comment by jeff1evesque** [comment]
I think I [solved](https://github.com/jeff1evesque/machine-learning/issues/2642#issuecomment-233229002) my use case.  However, is it bad practice to have the following assertion:

```python
...
    assert client.post(
        get_endpoint(),
        headers={'Content-Type': 'application/json'},
        data=get_sample_json('svm-data-new.json', 'svm')
    )
...
```

**Comment by vitalk** [comment]
- Flask [response object](http://flask.pocoo.org/docs/0.11/api/#flask.Response) has no attribute `code`, e.g. use `status_code` or `status`

- You should explicitly define which methods are supported while registering your route:

    ```python
    def test_load_data(live_server, client):
	@live_server.app.route('/load-data/', methods=['POST'])
	def load_data():
	    pass
    
	live_server.start()
	
	res = client.post(url_for('load_data'), data={})
	assert res.status_code == 200
    ```

**Comment by jeff1evesque** [comment]
@vitalk, if you don't mind, I could add some documentation regarding the above `client.post`.  I would have this done by this coming Thursday evening (hoping tomorrow).  When I submit a corresponding pull request, I could make any edits, or stylistic changes you prefer.

**Comment by vitalk** [comment]
@jeff1evesque it would be great!
