### ISSUE TITLE
License file is missing from manifest

### ISSUE THREAD

**Issue by sodre** [pytest-dev/pytest-flask#68]
I am packaging pytest-flask and I noticed that the license file missing from the pypi distribution. When you get a chance, can you add it  to the MANIFEST and regenerate pypi files?

ref: conda-forge/staged-recipes#3251

**Comment by northernSage** [comment]
As of [1.0.0](https://pypi.org/project/pytest-flask/) both wheel and source distributions bundle the LICENSE file.
