### ISSUE TITLE
Any examples of usage pattern?

### ISSUE THREAD

**Issue by ghost** [pytest-dev/pytest-flask#7]
I'm new to both py.test and Flask, and find it difficult to understand what goes where as far as testing is concerned :(

**Comment by st3fan** [comment]
@vitalk This is a great example that got me going. Why not just copy it verbatim to the documentation?

**Comment by nicoddemus** [comment]
@st3fan that's a great idea, perhaps you could open a PR with that? 😉

**Comment by senaps** [comment]
running the example above, im getting :

`fixture 'client' not found`
