### ISSUE TITLE
Pytest failing on error that is handled in app/__init__.py

### ISSUE THREAD

**Issue by Audace** [pytest-dev/pytest-flask#73]
I have a custom error I raise within one resource in my flask app. It's defined as such:
```
class BotAlreadyExists(Exception):
    status_code = 400

    def __init__(self, message='Bot already exists for this slack team', status_code=None, payload=None):
        Exception.__init__(self)
        self.message = message
        if status_code is not None:
            self.status_code = status_code
        self.payload = payload

    def to_dict(self):
        rv = dict(self.payload or ())
        rv['message'] = self.message
        return rv
```
In `app/__init__.py`, I use a decorator to handle this exception so that I get a 400 instead of 500 error as well as a useful message.
```
    @app.errorhandler(BotAlreadyExists)
    def handle_bot_already_exists_usage(error):
        response = jsonify(error.to_dict())
        response.status_code = error.status_code
        return response
```
This works perfectly when running locally, however, when I run a functional test using pytest / pytest-flask, it's as if the decorator never has an effect. Rather than returning the error message with a HTTP 400 status, the test fails because of the exception. Why is the flask app correctly handling the exception locally but failing to when testing?

**Comment by Audace** [comment]
Resolved by updating the app config in the fixture and setting `TESTING=True`. This matters because the underlying flag `PROPAGATE_EXCEPTIONS` needs to be `True`. 

Why is `Testing=True` not automatically set by pytest-flask? Seems like a reasonable thing to do.

**Comment by northernSage** [comment]
> Why is Testing=True not automatically set by pytest-flask? Seems like a reasonable thing to do.

I can't see any potential problems with this at first, so I would be glad to review a PR with a proposition. For now I'm closing this since the issue appears to have been solved.
