### ISSUE TITLE
Equalize pypi 0.10.0 tarball contents with github's repository 0.10.0 tag

### ISSUE THREAD

**Issue by irregulator** [pytest-dev/pytest-flask#75]
Hi, 

I would like to package `pytest-flask` in [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816713). I noticed that the tarball provided by [PyPI](https://pypi.python.org/pypi/pytest-flask#downloads) and the the tarball procuded with `git archive 0.10.0` on this repository slightly differ. Namely:
```
➜  localhost /tmp/pytest-flask  diff -r github pypi
Only in github: .gitignore
Only in github: Makefile
Only in pypi: PKG-INFO
Only in pypi: pytest_flask.egg-info
diff -r github/setup.cfg pypi/setup.cfg
2a3,8
> 
> [egg_info]
> tag_build = 
> tag_date = 0
> tag_svn_revision = 0
> 
Only in github: tests
Only in github: .travis.yml
```

It would greatly help my Debian packaging effort if these tarballs were exactly the same.
Please consider fixing this. Thanks.

**Comment by irregulator** [comment]
Just to be clear, my request concerns `setup.cfg` and `Makefile` files, as well as the `tests` directory. Thanks.

**Comment by nicoddemus** [comment]
@irregulator sorry for the silence on this. Can you generate the debian package using `0.11.0`? It should contain all the files from the repository, as we now use `setuptools_scm` to manage versions and it includes by default all version-controlled files.

**Comment by irregulator** [comment]
@nicoddemus indeed, thanks!

I did package version 0.11.0 successfully and I hope the package will soon be accepted by some debian developer.

**Comment by vitalk** [comment]
Thanks @irregulator!
