### ISSUE TITLE
Any word from the maintainer?

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-flask#76]
Hi everyone,

As #72 and #58 shows, people are worried that we haven't had a release in 2 years and there are open PRs waiting to be merged.

Does anybody have other means to contact @vitalk? 

Also, is anybody else willing to step up and help maintain `pytest-flask`? (pinging @steenzout as he has contributed with `pytest-flask` in the past).

**Comment by nicoddemus** [comment]
Thanks! I posted a tweet mentioning him. 👍

**Comment by vitalk** [comment]
Hi everyone,

Sorry for a long delay. I'm going to review of the pending PRs within this week. Thank you for patience.

**Comment by nicoddemus** [comment]
Thanks @vitalk for reaching out!

**Comment by ethier** [comment]
❓ @vitalk Would it be worth asking the community if someone else wants to maintain/assist? Want to be respectful of your efforts and time.
