### ISSUE TITLE
debugging live_server crash

### ISSUE THREAD

**Issue by fgregg** [pytest-dev/pytest-flask#93]
Hi there!

Thanks for the great library. 

I have a test like this

```python
@pytest.mark.usefixtures('live_server')
def test_cookie_getting(setup):
    sesh = requests.Session()

    username = 'foo'
    password = 'bar'

    response = sesh.post(
        url_for('security.login', _external=True),
        data={'email': username, 'password': password, 'next': None},
    )

    ...
```

When the requests makes the post, it kills the server. The test ends up exiting with a `Connection aborted` exception.

 I'm not sure why the server is halting. Do you have suggestions for getting messages or tracebacks from live_server?

**Comment by fgregg** [comment]
Possible clue. Sometimes I get this traceback in the pytest output:

```python
----------------------------- Captured stderr call -----------------------------
objc[28861]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[28861]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

**Comment by northernSage** [comment]
Hey @fgregg, thanks for letting us know about the issue. I have created a [minimal example](https://github.com/northernSage/pytest-flask-issue-93) with the provided test, but I'm afraid I wasn't able to reproduce the crash.

Test run output:

> platform darwin -- Python 3.7.8, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
> plugins: flask-1.0.0
> collected 1 item                                                                                                                                                      
> 
> tests/test_live_server.py .                                                                                                                 [100%]
> 
> ===========================1 passed in 5.17s================================

Could you please provide more details about your environment? our perhaps (even better) a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by northernSage** [comment]
Closing for now, feel free to open to provide the necessary information.
